import type {
  goalStrategyAssignments,
  goals,
  strategies,
  students,
  users,
  userStudentAssignments,
  workspaces,
} from "@/db/schema";

const createdAt = new Date("2026-09-01T15:00:00.000Z");
const updatedAt = new Date("2026-09-01T15:00:00.000Z");

export const SYNTHETIC_SEED_IDS = {
  workspace: "10000000-0000-4000-8000-000000000001",
  teacher: "20000000-0000-4000-8000-000000000001",
  assignedAssistant: "20000000-0000-4000-8000-000000000002",
  unassignedAssistant: "20000000-0000-4000-8000-000000000003",
  river: "30000000-0000-4000-8000-000000000001",
  sage: "30000000-0000-4000-8000-000000000002",
  micah: "30000000-0000-4000-8000-000000000003",
  riverDirectionsGoal: "40000000-0000-4000-8000-000000000001",
  riverHelpGoal: "40000000-0000-4000-8000-000000000002",
  riverPlayGoal: "40000000-0000-4000-8000-000000000003",
  sageTransitionsGoal: "40000000-0000-4000-8000-000000000004",
  sageChoicesGoal: "40000000-0000-4000-8000-000000000005",
  micahTurnTakingGoal: "40000000-0000-4000-8000-000000000006",
  micahCleanupGoal: "40000000-0000-4000-8000-000000000007",
  visualCueStrategy: "50000000-0000-4000-8000-000000000001",
  visualCueAssignment: "60000000-0000-4000-8000-000000000001",
} as const;

export const syntheticSeedData = {
  workspaces: [
    {
      id: SYNTHETIC_SEED_IDS.workspace,
      name: "Sunrise Room — Synthetic",
      timezone: "America/Los_Angeles",
      createdAt,
    },
  ] satisfies Array<typeof workspaces.$inferInsert>,
  users: [
    {
      id: SYNTHETIC_SEED_IDS.teacher,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "Demo teacher",
      email: "teacher@evidence-loop.example.invalid",
      role: "TEACHER",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.assignedAssistant,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "Demo assistant — assigned",
      email: "assigned-assistant@evidence-loop.example.invalid",
      role: "ASSISTANT",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.unassignedAssistant,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "Demo assistant — unassigned",
      email: "unassigned-assistant@evidence-loop.example.invalid",
      role: "ASSISTANT",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
  ] satisfies Array<typeof users.$inferInsert>,
  students: [
    {
      id: SYNTHETIC_SEED_IDS.river,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "River",
      group: "AM_MW",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.sage,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "Sage",
      group: "AM_TTH",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.micah,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      displayName: "Micah",
      group: "PM",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
  ] satisfies Array<typeof students.$inferInsert>,
  userStudentAssignments: [
    {
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      userId: SYNTHETIC_SEED_IDS.assignedAssistant,
      studentId: SYNTHETIC_SEED_IDS.river,
      createdAt,
    },
    {
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      userId: SYNTHETIC_SEED_IDS.assignedAssistant,
      studentId: SYNTHETIC_SEED_IDS.sage,
      createdAt,
    },
  ] satisfies Array<typeof userStudentAssignments.$inferInsert>,
  goals: [
    {
      id: SYNTHETIC_SEED_IDS.riverDirectionsGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.river,
      title: "Following directions",
      objectiveText:
        "Follow a one- or two-step classroom direction during a familiar routine.",
      domain: "Receptive Communication",
      targetScore: 4,
      expectedFrequency: "Daily",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 0,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.riverHelpGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.river,
      title: "Requesting help",
      objectiveText:
        "Use a word, sign, or communication tool to request help during a challenging activity.",
      domain: "Social Communication",
      targetScore: 4,
      expectedFrequency: "Daily",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 1,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.riverPlayGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.river,
      title: "Joining play",
      objectiveText:
        "Approach a peer activity and participate for at least one exchange.",
      domain: "Social Emotional",
      targetScore: 3,
      expectedFrequency: "Three times weekly",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 2,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.sageTransitionsGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.sage,
      title: "Transitioning between activities",
      objectiveText:
        "Move to the next classroom activity after a visual or verbal transition cue.",
      domain: "Adaptive",
      targetScore: 3,
      expectedFrequency: "Daily",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 0,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.sageChoicesGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.sage,
      title: "Communicating a choice",
      objectiveText:
        "Indicate a choice between two classroom options using a word, sign, or communication tool.",
      domain: "Social Communication",
      targetScore: 4,
      expectedFrequency: "Daily",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 1,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.micahTurnTakingGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.micah,
      title: "Taking turns",
      objectiveText:
        "Wait for and take one turn during a short adult-supported peer activity.",
      domain: "Social Emotional",
      targetScore: 3,
      expectedFrequency: "Three times weekly",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 0,
      version: 1,
      createdAt,
      updatedAt,
    },
    {
      id: SYNTHETIC_SEED_IDS.micahCleanupGoal,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      studentId: SYNTHETIC_SEED_IDS.micah,
      title: "Participating in cleanup",
      objectiveText:
        "Put away classroom materials when the cleanup routine begins.",
      domain: "Adaptive",
      targetScore: 3,
      expectedFrequency: "Daily",
      status: "ACTIVE",
      activeFrom: "2026-09-01",
      position: 1,
      version: 1,
      createdAt,
      updatedAt,
    },
  ] satisfies Array<typeof goals.$inferInsert>,
  strategies: [
    {
      id: SYNTHETIC_SEED_IDS.visualCueStrategy,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      name: "Visual cue and wait time",
      purpose:
        "Support following a familiar direction while allowing time for an independent response.",
      instructions:
        "Show one visual cue, give the direction once, then wait five seconds before adding support.",
      fidelityPrompt: "Was the visual cue and wait time used as planned?",
      version: 1,
      status: "ACTIVE",
      createdByUserId: SYNTHETIC_SEED_IDS.teacher,
      createdAt,
      updatedAt,
    },
  ] satisfies Array<typeof strategies.$inferInsert>,
  goalStrategyAssignments: [
    {
      id: SYNTHETIC_SEED_IDS.visualCueAssignment,
      workspaceId: SYNTHETIC_SEED_IDS.workspace,
      goalId: SYNTHETIC_SEED_IDS.riverDirectionsGoal,
      strategyId: SYNTHETIC_SEED_IDS.visualCueStrategy,
      strategyVersion: 1,
      startsOn: "2026-09-15",
      reason: "Collect fictional usability data with a concise strategy reminder.",
      plannedReviewOn: "2026-10-15",
      status: "ACTIVE",
      createdAt,
      updatedAt,
    },
  ] satisfies Array<typeof goalStrategyAssignments.$inferInsert>,
} as const;
